config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/flats", to: "flats#index" # static route
  get "/cheap-flats", to: "flats#cheap", as: "cheap"
  get "/flats/:id", to: "flats#show", as: "flat" # dynamic route
  # get "/best-flats", to: "flats#best"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats, only: [:index, :show, :cheap]

  def index
  end

  def show
    id = params[:id].to_i
    @flat = @flats.find { |flat| flat["id"] == id }
  end

  def cheap
    @cheap_flats = @flats.select {|flat| flat['price'] < 100}
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(URI.open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/cheap.html.erb
<div class="container">
  <div class="row">
    <% @cheap_flats.each do |flat| %>
      <div class="col-4">
        <img src="<%= flat['imageUrl'] %>" alt="">
        <p><%= flat['name'] %>, $ <%= flat['price'] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<p>hello from our new page</p>

<%= link_to "discover cheap flats", cheap_path, class: "btn btn-primary" %>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <%= link_to "visit this flat", flat_path(flat['id']) %>
        <img src="<%= flat['imageUrl'] %>" alt="">
        <p><%= flat['name'] %>, $ <%= flat['price'] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<p>this is the page of</p>
<h3><%= @flat['name'] %></h3>

<%= link_to "back to all flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>